name: Deploy to GitHub Pages

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: build
        run: |
          go build -C generator -o ../deploy/generator

      - name: generate
        run: |
          bash deploy/deploy.sh

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.md
          files: docs/assets/info-latest.zip
          name: latest
          make_latest: 'true'
